version: '2'
services:
 mysqldb:
  container_name: mysqldb
  image: mysql:8
  restart: unless-stopped
  environment:
   MYSQL_ROOT_PASSWORD: root
  ports:
   - 3306:3306
  volumes:
   - /home/ProjetDevops/volsql/data:/var/lib/mysql
 spring_app:
  image: MouhebBenAbdelkader/ExamThourayaS2-1.0
  container_name: examThourayaS2
  restart: on-failure
  ports:
   - 8085:8086
  depends_on:
   - mysqldb